# Placeholder - populated as REST/WebSocket resources are added.
quarkus.application.name=grimtorrenter
#quarkus.log.category."com.grimtorrenter.engine.torrent.TorrentSession".level=DEBUG
grimtorrenter.listen-port=7881